version: "2"
services:
  web:
    image: jrszapata/numbers-to-words
    build: .
    volumes: 
      - ./:/var/www/html
    ports:
      - 8095:80
    environment:
      - VIRTUAL_HOST=numbers.dev,www.numbers.dev
    networks:
      - proxy

networks:
  proxy:  
    external:
      name: prx_proxy_net